### ISSUE TITLE
Adding Heartbeats and CustomChecks to the NServiceBus.MessagingBridge

### ISSUE THREAD

**Issue by Floopy-Doo** [Particular/NServiceBus.MessagingBridge#210]
### Description

The NServiceBus.MessagingBridge needs to be able to report `heartbeats` and `custom checks` to ServiceControl so that end users can know that their running bridge applications are healthy. 

Users running the bridge can configure `heartbeats` and `custom checks` for each transport configured in the bridge. This will allow health messages to each ServiceControl instance for configured transports. 

This implementation does not require referencing any NuGet packages other than NServiceBus.MessagingBridge to access the `heartbeats` or `custom checks` functionality. It uses the same public API as the existing heartbeats and custom checks and is compatible with any custom checks that users may already be using in other NServiceBus endpoints.

### Documentation

[Configuring Heartbeats and CustomChecks](https://docs.particular.net/nservicebus/bridge/configuration?#monitoring)

### Original issue content
We are using the bridge as a vital part to transition our system from MSMQ to AzureServiceBus step by step. 
Therefore, we would like to monitor the running condition of the bridge closely.

The current implementation does not allow the NServiceBus.Heartbeat and NServiceBus.CustomCheck packages to be used in unison.
We would like to use ServiceControl for verifying the condition of our system.

**Comment by DavidBoike** [comment]
Next time we focus on enhancing the Bridge we'll be sure to consider this. Thanks!

**Comment by Floopy-Doo** [comment]
any update on this feature?

**Comment by ramonsmits** [comment]
@Floopy-Doo We don't have any work schedule on the bridge at the moment and are focussing on other priorities. Thanks for your comment as that makes it clear that we need to better communicate what we are currently prioritizing.

**Comment by awright18** [comment]
Will be released in version 2.2 of NServiceBus.MessagingBridge

**Comment by awright18** [comment]
@Floopy-Doo This feature has been implemented in version 2.2.0. 

- [Announcement](https://discuss.particular.net/t/nservicebus-messagingbridge-2-2-0-minor-release-available/3855)

- [Configuring Heartbeats and CustomChecks](https://docs.particular.net/nservicebus/bridge/configuration?#monitoring)
