### ISSUE TITLE
Handle pub/sub better in native pub/sub transports

### ISSUE THREAD

**Issue by SzymonPobiega** [Particular/NServiceBus.MessagingBridge#267]
The current handling of pub/sub requires manual configuration in the bridge code. It is not feasible for environments with lots of subscribers. Whenever the topology changes, the bridge needs to be re-deployed.

See the following  issue in Router repo:

- https://github.com/SzymonPobiega/NServiceBus.Router/issues/52#issuecomment-1543537246

**Comment by dvdstelt** [comment]
Closed in favor of [this issue](https://github.com/Particular/NServiceBus.MessagingBridge/issues/292). It explains some of the history and ideas of why the bridge works the way it does and how to potentially solve it.
