### ISSUE TITLE
Default error queue validation

### ISSUE THREAD

**Issue by ramonsmits** [Particular/NServiceBus.MessagingBridge#74]
After reading https://docs.particular.net/nservicebus/bridge/configuration#recoverability-error-queue I wondered why the default cannot be `error`.

> Note that the default error queue used by other platform components can not be used to enable bridging of the system-wide error queue since a bridged queue may not be used as the error queue.

Wouldn't it simply possible to verify if the bridge configuration isn't bridging the configured error queue?

Also, wouldn't the bridge be able to spot this based on the fact that such messages would have a `FailedQ` header?

**Comment by dvdstelt** [comment]
@ramonsmits Does this answer your questions?
